name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:ubuntu
    steps:
      # نسخ ملفات المشروع
      - uses: actions/checkout@v3

      # تحديث pip وتثبيت buildozer
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer

      # بناء APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # رفع APK كـ artifact لتنزيله من GitHub
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
